### ISSUE TITLE
[Question]: How do you pass data to a previous route using the new router service?

### ISSUE THREAD

**Issue by ScottAtRedHawk** [FilledStacks/academy#27]
Hi @FilledStacks,
I feel like the question is self explanatory, but I'll add more info.

Assume I have routes A and B. Route B returns a `bool` to route A.

```dart
// view model A
Future<void> onTap() async {
  dynamic /* bool */ result = await _routerService.navigateTo(BViewRoute());
  _logger.d(result); // this is always null and the navigateTo call returns immediately
}
```

 I've tried `_routerService.pop(true);` and `_routerService.back(result: true);` on route B, but nothing happens. No navigation occurs.

On route B, when I do `_routerService.navigateBack();`, I'm navigated back, but that method doesn't accept any data to return to the previous route. Can you please help?

Keep up the AWESOME work!

**Comment by FilledStacks** [comment]
@ScottAtRedHawk There might be a bug, but the latest version of stacked_services passes the result. 

```dart
  Future<bool> pop<T extends Object?>([T? result]) => router.pop(result);

  /// An alias for pop for better readability
  Future<bool> back<T extends Object?>({T? result}) => router.pop(result);
```

I just recently forked this functionality from AutoRoute so there might be a bug or missing functionality that I haven't picked up yet. What version of stacked_services are you using?

**Comment by ferrarafer** [comment]
I just made some tests and I can confirm the bug, I didn't find the root of the issue yet.

**Comment by ferrarafer** [comment]
@ScottAtRedHawk please replace your code with the following code until we discuss another implementation with @FilledStacks . Let me know if it doesn't work, but I tried it and works for me.

The problem are not pop or back methods, is `navigate` method which is not awaiting the call like push method.

```dart
// view model A
Future<void> onTap() async {
  final result = await _routerService.router.push(const BViewRoute());
  _logger.d(result); // this is always null and the navigateTo call returns immediately
}

```

**Comment by ferrarafer** [comment]
@FilledStacks do we close this?

**Comment by ScottAtRedHawk** [comment]
@ferrarafer It can be closed as far as I'm concerned. It worked and I forgot to comment again. Sorry!

**Comment by ferrarafer** [comment]
@ScottAtRedHawk with latest version we changed navigate with push by default under the hood so you can simple await a `navigateTo` call without using the router.
